<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="LAPTOP-66KHMHA0" failures="1" tests="3" name="Test" time="42.985" errors="0" timestamp="2025-10-07T11:04:30 IST">
  <testcase classname="testscript.LoginTest" name="verifyloginwithValidCredentials" time="7.45">
    <skipped/>
  </testcase> <!-- verifyloginwithValidCredentials -->
  <testcase classname="testscript.LoginTest" name="verifyloginwithValidCredentials" time="4.471">
    <skipped/>
  </testcase> <!-- verifyloginwithValidCredentials -->
  <testcase classname="testscript.LoginTest" name="verifyloginwithValidCredentials" time="3.165">
    <failure type="java.lang.AssertionError" message="Login is not successfull with valid credentials expected [https://groceryapp.uniqassosiates.com/admin/home] but found [https://groceryapp.uniqassosiates.com/admin]">
      <![CDATA[java.lang.AssertionError: Login is not successfull with valid credentials expected [https://groceryapp.uniqassosiates.com/admin/home] but found [https://groceryapp.uniqassosiates.com/admin]
at testscript.LoginTest.verifyloginwithValidCredentials(LoginTest.java:31)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- verifyloginwithValidCredentials -->
  <testcase classname="testscript.LoginTest" name="verifyloginwithInvalidCredentials" time="0.0">
    <ignored/>
  </testcase> <!-- verifyloginwithInvalidCredentials -->
  <testcase classname="testscript.LoginTest" name="verifyloginwithValidUsernameInvalidpassword" time="0.0">
    <ignored/>
  </testcase> <!-- verifyloginwithValidUsernameInvalidpassword -->
  <testcase classname="testscript.LoginTest" name="verifyloginwithInvalidusernameValidPassword" time="0.0">
    <ignored/>
  </testcase> <!-- verifyloginwithInvalidusernameValidPassword -->
</testsuite> <!-- Test -->
